### PR TITLE
Fix decoding of tokens having a single scope

### LINKED ISSUE #20: Unable to decode tokens containing a single scope
Given a configuration with a single scope

```ruby
Rails.application.config.middleware.use OmniAuth::Builder do
  provider :eve_online_sso,
    ENV["EVE_ONLINE_SSO_CLIENT_ID"],
    ENV["EVE_ONLINE_SSO_SECRET_KEY"],
    scope: "esi-calendar.read_calendar_events.v1"
end
```

Parsing the OAuth token fails with an error

> NoMethodError: undefined method `join' for "esi-calendar.read_calendar_events.v1":String 

```ruby
# omniauth-eve_online-sso (0.4.0) lib/omniauth/strategies/eve_online_sso.rb:38:in `block in raw_info'
def raw_info
  @raw_info ||= JWT.decode(access_token.token, nil, false)
    .find { |element| element.keys.include?("scp") }.tap do |hash|
      hash["character_id"] = hash["sub"].split(":")[-1]
      hash["scopes"] = hash["scp"].join(" ") # <---------- Always expecting an Array
      hash["token_type"] = hash["sub"].split(":")[0].capitalize
      hash["expires_on"] = hash["exp"]
    end
end
```

### PR DESCRIPTION
**Pull request by lunohodov**
Closes #20

This PR adds

* support for parsing tokens containing a single scope
* basic tests

### CODE REVIEW

**Review by biow0lf — APPROVED** [review]

**Comment by biow0lf** [comment]
Update CHANGELOG, bump version and merge then to master. Plus, create release tag. (Don't forget to push tags!)

**Comment by biow0lf** [comment]
@lunohodov give me your email for/from rubygems.org and I will add you rights for push omniauth-eve_online-sso.

**Comment by lunohodov** [comment]
@biow0lf Email is my GitHub username at gmail.

**Comment by lunohodov** [comment]
@biow0lf Any info on v0.5 release?

**Pull request merged**
